config/routes.rb
Rails.application.routes.draw do
  
  resources :stories
  resources :headlines
  resources :leadlines
  resources :quotes
  resources :atoms
  
  get 'news' => 'news#index'
  get 'news/:id' => 'news#show'
  post 'make_headline_active/:id' => 'headlines#make_headline_active', as: :make_headline_active
  post 'make_leadline_active/:id' => 'leadlines#make_leadline_active', as: :make_leadline_active
  

end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :story_elements
  has_many :atoms, :through => :story_elements, :source => :element, :source_type => 'Atom'
  has_many :quotes, :through => :story_elements, :source => :element, :source_type => 'Quote'
  has_many :headlines
  has_many :leadlines
  has_many :atom_citations, :through => :atoms, :source => :citations 
  has_many :quote_citations, :through => :quotes, :source => :citations
  has_and_belongs_to_many :similar_stories, class_name: "Story", foreign_key: "story_id", association_foreign_key: "similar_story_id", join_table: "similar_stories"  
  has_many :related_elements
  acts_as_taggable_on :themes
  belongs_to :section
end

# Returns an array Atoms and Quotes associated with this Story
def get_all_elements
  self.atoms + self.quotes
end

# Returns and array of Citations of all associated elements
def get_all_citations 
  self.atom_citations + self.quote_citations
end

# Returns the active Headline line
def get_active_headline  
  if Headline.exists?(self.active_headline_id)  
    self.headlines.find(self.active_headline_id).headline
  else
    false
  end
end

# Returns the active Leadline line
def get_active_leadline  
  if Leadline.exists?(self.active_leadline_id)
    self.leadlines.find(self.active_leadline_id).leadline
  else
    false
  end
end

# Returns the title of the associated Section
def filed_under?
  self.section.title
end


# Story elements helper functions.
# The story_elements is much like an array.
# And array we'll call the position stack.
# Starts from 1 on, 1 being the top,
#
# manipulators: pop, insert, push, append, replace,
# make_consistent
# utilities: consistent?

# pop - pop off the last position in the stack
def pop
end

# insert - insert position somewhere in the stack, and move all subsequent positions down one
def insert
end

# push - move down all positions and put a new position at the beginning
def push
end

# append - add a position at the end of the stack
def append
end

# replace - put a new element into a position without disturbing any other position
def replace
end

# consistent? - are there numerical gaps in the order of positions, 1, 2, 4, 5, 10, returns true|false
def consistent?
  stack = self.story_elements
  key = stack.sum(:position)
  len = stack.length 
  
    if len % 2 == 0 # even len
      checksum = (len / 2) * (1 + len)
    else
      checksum = ((len / 2) + 1) * len
    end 

    if checksum == key
      return true
    else
      return false
    end
end

# make_consistent - slide up every position, 1, 2, 4, 5, 10 => 1, 2, 3, 4, 5
def make_consistent
  if !self.consistent?
      stack = self.story_elements.order(position: :asc)
      order = 1    
      stack.each do |s|
        pos = StoryElement.find(s.id)
        pos.position = order
        pos.save
        order += 1
      end
    return true
  else 
    return true
  end  
end

public :get_all_elements, :get_all_citations, :get_active_headline, :get_active_leadline, :filed_under?, :pop, :insert, :push, :append, :replace, :consistent?, :make_consistent

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  layout "authoring"

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
    @sections = Section.all
  end

  # GET /stories/1/edit
  def edit
    @story_content = @story.get_all_elements
    @sections = Section.all
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new()
    @story.section_id = params[:story][:section]
    @story.subject = params[:subject]
    # @story.mast_url = ""
    # @story.thumb_url = ""
    
    if !params[:theme_tags].empty?
        input = params[:theme_tags]
        input = input.gsub('"', '')
        input.slice!(0)
        input = input.chop
      @story.theme_list.add(input, parse: true)
    end
      
    respond_to do |format|
      if @story.save
        hl = @story.headlines.create(headline: params[:headline], story_id: @story.id)
        ll = @story.leadlines.create(leadline: params[:leadline], story_id: @story.id)
        @story.active_headline_id = hl.id
        @story.active_leadline_id = ll.id
        @story.save
        # Need to add theme tags       
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    @story.subject = params[:storyEditSubject]
    @story.section_id = story_params[:section_id]
    @story.theme_list = params[:storyEditTags]
    
    respond_to do |format|
      if @story.save
        format.html { redirect_to edit_story_url(@story), notice: 'Story was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params[:story].permit(:subject, :mast_url, :thumb_url, :headline, :leadline, :section_id, :storyEditSubject, :element_id)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_authoring_content_modal.html.erb
<!-- A modal to be activated by a button, via data attributes -->
<div class="modal fade" id="contentEditModal" tabindex="-1" role="dialog" aria-labelledby="contentEditModal" aria-hidden="true" aria-describedby="" data-backdrop="static">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <span class="modal-title h4"><small>Topic: </small><span id="modalTopicTitle"></span></span>
        <button type="button" class="close pull-right" aria-label="Close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
      </div><!-- modal-header -->
             
      <div class="modal-body">
        <div class="row">
          <div class="col-xs-5"><p class="pa-content">
            <span id="elementContent"></span></p>
          </div><!-- element content -->
          
          <%= form_tag(atom_path(), method: 'patch', id: :editQuoteForm) %>
          <div class="col-xs-7">
             <%= hidden_field_tag('story_id', @story.id) %>
             <%= hidden_field_tag('element_id', id: 'element_id') %>
             <%= hidden_field_tag('element_type', 'Atom') %>
            
            <div class="form-group">
                <label for="contentEditTopic" class="control-label small">Topic:</label>
                <input class="form-control input-sm" type="text" name="contentEditTopic" id="contentEditTopic">
            </div>
            
            <div class="form-group">
                <label for="contentEditContent" class="control-label">Content:</label>
                <textarea class="form-control input-sm" name="contentEditContent" id="contentEditContent" rows=7 oninput="charCount('contentEditContent', 'contentEditContentCharNum')"></textarea>
                <div id="contentEditContentCharNum" class="text-muted small">0 characters</div>
            </div>
           
            <div class="form-group"> <!-- Theme Tags Field -->
              <label for="contentEditThemeTags" class="control-label">Theme Tags:</label>
              <textarea class="form-control" name="contentEditThemeTags" id="contentEditThemeTags" rows=2></textarea>
            </div>
              
            <div class="form-group"> <!-- Theme Tags Field -->
              <label for="contentEditContextTags" class="control-label">Context Tags:</label>
              <textarea class="form-control" name="contentEditContextTags" id="contentEditContextTags" rows=2></textarea>
              <p class="help-block small">Tags are seperated by a comma.</p>
            </div>          
              
            </div><!-- content form fields -->
          
          </div><!-- row -->
        </div><!-- modal body -->
        
      <div class="modal-footer">
          <div class="form-group">
            <button type="reset" class="btn btn-warning pull-left" onclick="resetTextArea('contentEditContent', 'contentEditContentCharNum')">Reset form</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save changes</button>
          </div> <!-- controls -->
        </div> <!-- modal footer --> 
      </form> <!-- form -->
      
    </div><!-- modal-content -->
  </div><!-- modal-dialog -->
</div><!-- modal wrapper -->

<script>
  
  /* commented out because function charCount() and function resetTextArea are included in the quote modal
  function charCount(in_ele, out_ele) {
      var len = document.getElementById(in_ele).value.length;
      document.getElementById(out_ele).innerHTML = len + " Characters";
  }
  
  function resetTextArea (in_ele, out_ele){
    var elementExists = document.getElementById(in_ele);
    var displayElementExists = document.getElementById(out_ele);
    
    if (elementExists != null) {
      document.getElementById(in_ele).value = '';
    }
    if (displayElementExists != null) {
      document.getElementById(out_ele).innerHTML = "0 characters"
    }
  } */ 
  
// Modal scripts
$('#contentEditModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget) // Button that triggered the modal
      var element_id = button.data('element-id') // Extract info from data-* attributes
      var topic = button.data('topic')
      var content = button.data('content')
      var theme_tags = button.data('theme-tags')
      var context_tags = button.data('context-tags')

      var modal = $(this)
      modal.find('#element_id').attr('value', element_id)
      modal.find('#contentEditTopic').val(topic)
      modal.find('#contentEditContent').val(content)
      var content_len = $('#contentEditContent').val().length
      modal.find('#contentEditContentCharNum').text(content_len + " characters")
      
      modal.find('#modalTopicTitle').text(topic)
      modal.find('#elementContent').text(content)
      modal.find('#contentEditThemeTags').val(theme_tags)
      modal.find('#contentEditContextTags').val(context_tags)
    })
</script>

app/views/stories/_authoring_elements_panel.html.erb
<div class="panel panel-default">
<div class="panel-heading">
  <h3 class="panel-title">Content & Positions
    <span class="badge pull-right small">
      <% eleCount = @story.story_elements.count %>
      <%= pluralize(eleCount,'position') %></span></h3> <!-- title and counter -->
</div>  <!-- header -->

<ul class="list-group"><li class="list-group-item"><div class="btn-group btn-group-xs" role="group" aria-label="...">
    <div class="btn-group btn-group-xs" role="group">
      <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        <i class="fa fa-plus"></i> New Position <span class="caret"></span>
      </button> <!-- new position button -->
      <ul class="dropdown-menu" role="menu">
        <li><a href="#" role="button" data-toggle="modal" data-target="#quoteNewModal"><i class="fa fa-quote-left"></i> New Quote</a></li>
        <li><a href="#" role="button" data-toggle="modal" data-target="#contentNewModal"><i class="fa fa-font"></i> New Content</a></li>
        <li><a href="#"><i class="fa fa-link"></i> Insert Existing Content</a></li>
      </ul> <!-- new position dropdown -->
    </div> <!-- new position btn group -->
    <button type="button" class="btn btn-default btn-xs">
      <i class="fa fa-bars"></i> Reorder Positions
</button> <!-- reorder button -->
  </div></li></ul> <!-- controls -->

<ul class="list-group">
  <%= render partial: "element_item", collection: @story.story_elements.order(position: :asc), as: :position %>
</ul> <!-- elements/position list group -->

<div class="panel-footer">footer</div>
</div> <!-- elements end -->

app/views/stories/_authoring_headlines_panel.html.erb
<div class="panel panel-default">
<div class="panel-heading">
    <h3 class="panel-title">Headlines
      <span class="badge pull-right small">
      <% hlCount = @story.headlines.count %>
      <%= pluralize(hlCount,'headline') %></span></h3> <!-- title and counter -->
  </div>  <!-- header -->

<ul class="list-group">    
  <% if @story.get_active_headline %>
  <li class="list-group-item active">
    <p class="pa-content"><%= @story.get_active_headline %></p>
  
    <p><div class="collapse" id="activeHeadlineEditForm">
    <div class="well well-sm">
      <%= form_tag(headline_path(@story.get_active_headline_id), method: 'patch') do %>
      <%= hidden_field_tag('story_id', @story.id) %>
      <div class="form-group" role="group">
        <%= text_area_tag(:headline, @story.get_active_headline, rows: 4, class: 'form-control input-sm') %>
      </div> <!-- textarea -->
      <div class="btn-group btn-group-xs" role="group" aria-label="...">
        <%= link_to('Close', '#activeHeadlineEditForm', class: 'btn btn-default', role: 'button', data: {toggle: 'collapse'}, aria_expanded: false, aria_control: 'activeHeadlineEditForm') %>
        <%= submit_tag('Save', class: 'btn btn-primary', data: { disable_with: 'Saving...' }) %></div> <!-- close, save btn group -->
    <% end %>  
    </div> <!-- well -->
  </div></p> <!-- collapse -->

    <p><%= form_tag(headline_path(@story.get_active_headline_id), method: 'delete') do %>
    <%= hidden_field_tag('story_id', @story.id) %>
    <div class="btn-group btn-group-xs" role="group" aria-label="...">
        <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#activeHeadlineEditForm"><i class="fa fa-pencil-square-o"></i> Edit</button>

         <%= submit_tag('Delete', class: 'btn btn-default btn-danger', data: {confirm: "Deleting the headline like this will permenantly destroy it. Are you sure you just don't want to add a new headline?"}) %>
        </div><% end %></p>
  </li> <!-- active headline -->
  <% else %>
  <li class="list-group-item list-group-item-danger text-center">
    <i class="fa fa-warning"></i> Warning -- No Active Headline!!<br>
      <span class="small">Please make one headline active.</span>
  </li> <!-- warning message -->
  <% end %>

<%= render partial: "headline_item", collection: @story.headlines, as: :headline %>

</ul> <!-- headlines list group -->

<div class="panel-footer">
<p><div class="collapse" id="newHeadlineCollapse" open=true >
          <div class="well well-sm">
            <%= form_tag(headlines_path, method: 'post') do %>
            <%= hidden_field_tag('story_id', @story.id) %>
            <div class="form-group" role="group">
            <%= text_area_tag(:headline, nil , rows: 4, class: 'form-control input-sm') %>
            </div> <!-- textarea -->
            <div class="btn-group btn-group-xs" role="group" aria-label="...">
              <%= link_to('Close', '#newHeadlineCollapse', class: 'btn btn-default', role: 'button', data: {toggle: 'collapse'}, aria_expanded: false, aria_control: 'newHeadlineCollapse') %>
            <%= submit_tag('Save', class: 'btn btn-primary', data: { disable_with: 'Saving...' }) %></div> <!-- close, save btn group -->
            <% end %>  
          </div> <!-- well -->
  </div></p><!-- collapse -->
<button type="button" class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#newHeadlineCollapse">New Headline</button>
</div> <!-- footer -->
</div> <!-- headline panel -->

app/views/stories/_authoring_leadlines_panel.html.erb
<div class="panel panel-default">
<div class="panel-heading">
    <h3 class="panel-title">Leadlines
      <span class="badge pull-right small">
      <% llCount = @story.leadlines.count %>
      <%= pluralize(llCount,'leadline') %></span></h3> <!-- title and counter -->
  </div>  <!-- header -->

<ul class="list-group">
  <% if @story.get_active_leadline %>
  <li class="list-group-item active">
    <p class="pa-content"><%= @story.get_active_leadline %></p>
  
    <p><div class="collapse" id="activeLeadlineEditForm">
    <div class="well well-sm">
      <%= form_tag(leadline_path(@story.get_active_leadline_id), method: 'patch') do %>
      <%= hidden_field_tag('story_id', @story.id) %>
      <div class="form-group" role="group">
        <%= text_area_tag(:leadline, @story.get_active_leadline, rows: 4, class: 'form-control input-sm') %>
      </div> <!-- textarea -->
      <div class="btn-group btn-group-xs" role="group" aria-label="...">
        <%= link_to('Close', '#activeLeadlineEditForm', class: 'btn btn-default', role: 'button', data: {toggle: 'collapse'}, aria_expanded: false, aria_control: 'activeLeadlineEditForm') %>
        <%= submit_tag('Save', class: 'btn btn-primary', data: { disable_with: 'Saving...' }) %></div> <!-- close, save btn group -->
    <% end %>  
    </div> <!-- well -->
  </div></p> <!-- collapse -->

    <p><%= form_tag(leadline_path(@story.get_active_leadline_id), method: 'delete') do %>
    <%= hidden_field_tag('story_id', @story.id) %>
    <div class="btn-group btn-group-xs" role="group" aria-label="...">
        <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#activeLeadlineEditForm"><i class="fa fa-pencil-square-o"></i> Edit</button>
         <%= submit_tag('Delete', class: 'btn btn-default btn-danger', data: {confirm: "Deleting the leadline like this will permenantly destroy it. Are you sure you just don't want to add a new leadline?"}) %>
        </div><% end %></p>
  </li> <!-- active leadline -->
  <% else %>
  <li class="list-group-item list-group-item-danger text-center">
    <i class="fa fa-warning"></i> Warning -- No Active leadline!!<br>
      <span class="small">Please make one leadline active.</span>
  </li> <!-- warning message -->
  <% end %>

<%= render partial: "leadline_item", collection: @story.leadlines, as: :leadline %>

</ul> <!-- leadlines list group -->

<div class="panel-footer">
<p><div class="collapse" id="newLeadlineCollapse" open=true >
          <div class="well well-sm">
            <%= form_tag(leadlines_path, method: 'post') do %>
            <%= hidden_field_tag('story_id', @story.id) %>
            <div class="form-group" role="group">
            <%= text_area_tag(:leadline, nil , rows: 4, class: 'form-control input-sm') %>
            </div> <!-- textarea -->
            <div class="btn-group btn-group-xs" role="group" aria-label="...">
              <%= link_to('Close', '#newLeadlineCollapse', class: 'btn btn-default', role: 'button', data: {toggle: 'collapse'}, aria_expanded: false, aria_control: 'newleadlineCollapse') %>
            <%= submit_tag('Save', class: 'btn btn-primary', data: { disable_with: 'Saving...' }) %></div> <!-- close, save btn group -->
            <% end %>  
          </div> <!-- well -->
  </div></p><!-- collapse -->
<button type="button" class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#newLeadlineCollapse">New Leadline</button>
</div> <!-- footer -->
</div> <!-- leadline panel -->

app/views/stories/_authoring_main_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <p><h3 class="panel-title">Filed under: 
      <mark><%= @story.filed_under? %></mark>
    </h3></p> <!-- section filing -->
    <p>Tagged themes: 
      <span class="text-info"><%= @story.theme_list %></span>
    </p> <!-- tags -->
  </div> <!-- header -->
  
  <div class="panel-body">
    <div class="center-block text-center">
      <p class="h2"><%= @story.subject %></p> <!-- story subject -->
      <p class="small">Created: 
        <mark><%= time_ago_in_words(@story.created_at) %> ago</mark> 
        | Updated: <mark><%= time_ago_in_words(@story.updated_at) %> ago</mark>
      </p> <!-- age, updated -->
      
    <p><div class="collapse" id="storyEditForm">
       <%= form_tag(story_url(@story), method: 'patch') do %>
         <div class="well well-sm form-horizontal">
          
            <div class="form-group"> 
                <label for="storyEditSubject" class="control-label col-sm-2">Subject:</label>
                <div class="col-sm-10"><%= text_field_tag('storyEditSubject', @story.subject, {class: 'form-control input-sm'}) %>
              </div>
            </div><!-- Subject field -->
          
            <div class="form-group"> 
                <label for="storyEditSection" class="control-label col-sm-2">Filed under section:</label>
                <div class="col-sm-10">
                  <%= collection_select(:story, :section_id, @sections, :id, :title, {prompt: false}, {class: 'form-control input-sm'}) %>
                </div>
            </div><!-- Section field -->
          
            <div class="form-group"> 
                <label for="storyEditTags" class="control-label col-sm-2">Theme tags:</label>
                <div class="col-sm-10">
                  <%= text_area_tag('storyEditTags', @story.theme_list, class: 'form-control input-sm') %>
                  <p class="help-block small pull-left">Comma separate tags.</p>
                </div>
            </div><!-- Tags field -->
          
            <div class="form-group">
              <div class="col-sm-12">
                <div class="btn-group btn-group-xs" role="group" aria-label="...">
                <%= link_to('Close', '#storyEditForm', class: 'btn btn-default', role: 'button', data: {toggle: 'collapse'}, aria_expanded: false, aria_control: 'activeHeadlineEditForm') %>
                <%= submit_tag('Save', class: 'btn btn-primary', data: { disable_with: 'Saving...' }) %></div>
              </div>
          </div>
        </div><!-- well -->
       <% end %>      
       </div></p> <!-- Collapse -->
    
      <p><div class="btn-group btn-group-xs" role="group" aria-label="..."><button type="button" class="btn btn-default btn-sm" data-toggle="collapse" data-target="#storyEditForm"><i class="fa fa-pencil-square-o"></i> Edit</button></div></p> 
    </div> <!-- masthead -->
  </div> <!-- body -->
</div> <!-- main top panel -->

<script>

</script>

app/views/stories/_authoring_new_content_position_modal.html.erb
<!-- A modal to be activated by a button, via data attributes -->
<div class="modal fade" id="contentNewModal" tabindex="-1" role="dialog" aria-labelledby="contentNewModal" aria-hidden="true" aria-describedby="" data-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <span class="modal-title h4">Create a new content postion.</span>
        <button type="button" class="close pull-right" aria-label="Close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
      </div><!-- modal-header -->
        
        <div class="modal-body">
        <div class="row">
          <%= form_tag(atoms_path(), method: 'post', id: :newAtomForm) %>
          <div class="col-xs-12">
             <%= hidden_field_tag('story_id', @story.id) %>
             <%= hidden_field_tag('element_id', id: 'element_id') %>
             <%= hidden_field_tag('element_type', 'Quote') %>            
            <div class="form-group">
                <label for="contentTopic" class="control-label">Topic:</label>
                <input class="form-control input-sm" type="text" name="contentTopic" id="contentTopic">
            </div> <!-- contentTopic -->
            
            <div class="form-group">
                <label for="contentContent" class="control-label">Content:</label>
                <textarea class="form-control input-sm" name="contentContent" id="contentContent" rows=7 oninput="charCount('contentContent', 'contentContentCharNum')"></textarea>
                <div id="contentContentCharNum" class="text-muted small">0 characters</div>
            </div> <!-- contentContent -->
           
            <div class="form-group">
              <label for="contentThemeTags" class="control-label">Theme Tags:</label>
              <textarea class="form-control" name="contentThemeTags" id="contentThemeTags" rows=2></textarea>
            </div> <!-- contentThemeTags -->
              
            <div class="form-group">
              <label for="contentContextTags" class="control-label">Context Tags:</label>
              <textarea class="form-control" name="contentContextTags" id="contentContextTags" rows=2></textarea>
              <p class="help-block small">Tags are seperated by a comma.</p>
            </div> <!-- contentContextTags -->
              
            </div><!-- content form fields -->
          </div><!-- row -->
        </div><!-- modal body -->
        
        <div class="modal-footer">
          <div class="form-group">
            <button type="reset" class="btn btn-warning pull-left" onclick="resetTextArea('contentContent', 'contentContentCharNum')">Reset form</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save changes</button>
          </div> <!-- controls -->
        </div> <!-- modal footer -->
      </form> <!-- form -->
      
    </div><!-- modal-content -->
  </div><!-- modal-dialog -->
</div><!-- modal wrapper -->

<script>
// counter and counterReset functions are included in the quoteEditModal
</script>

app/views/stories/_headline_item.html.erb
<!-- inactive headline list item -->

<% if @story.active_headline_id != headline.id %>
<li class="list-group-item">
  <%= headline.headline %>
  <% hl_collapse_name = 'headlineEditForm_' + headline.id.to_s %>
  <% hl_collapse_name_a = '#headlineEditForm_' + headline.id.to_s %>

<p><%= tag('div', class: 'collapse', id: hl_collapse_name, open: :true) %>
    <div class="well well-sm">
      <%= form_tag( headline_path(headline.id), method: 'patch') do %>
      <%= hidden_field_tag('story_id', @story.id) %>
       <div class="form-group" role="group">
         <%= text_area_tag(:headline, headline.headline , rows: 4, class: 'form-control input-sm') %>
      </div> <!-- textarea -->
       <div class="btn-group btn-group-xs" role="group" aria-label="...">
      <%= link_to('Close', hl_collapse_name_a, class: 'btn btn-default', role: 'button', data: {toggle: 'collapse'}, aria_expanded: false, aria_control: hl_collapse_name) %>
      <%= submit_tag('Save', class: 'btn btn-primary', data: { disable_with: 'Saving...' }) %></div> <!-- close, save btn group -->
      <% end %>  
  </div> <!-- well -->
</div></p> <!-- collapse -->

<p><div class="btn-toolbar" role="toolbar" aria-label="Toolbar">
  <%= form_tag( headline_path( headline.id ), method: :delete ) do %>
  <%= hidden_field_tag('story_id', @story.id) %>
  <div class="btn-group btn-group-xs" role="group" aria-label="Edit Delete button group">
     <%= link_to( hl_collapse_name_a, class: 'btn btn-default', role: 'button', type: 'button', data: {toggle: 'collapse'}, aria_expanded: false, aria_control: hl_collapse_name) do %><i class="fa fa-pencil-square-o"></i> Edit<% end %>
    <%= submit_tag( 'Delete', class: 'btn btn-default btn-danger', role: 'button', data: {confirm: "Deleting the headline like this will permenantly destroy it. Are you sure you just don't want to add a new headline?"}) %>
  <% end %>
  </div> <!-- edit, delete btn group -->

  <%= form_tag( make_headline_active_path( headline.id ), method: :post ) do %>
  <%= hidden_field_tag('story_id', @story.id) %>
  <div class="btn-group btn-group-xs" role="group" aria-label="Make Active">
    <button class="btn btn-default pull-right" role="button" type="submit"><i class="fa fa-star"></i> Make Active</button>
    <% end %>
  </div> <!-- active btn group -->    
</div></p> <!-- controls -->

</li><% end %> <!-- list item -->

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>