config/routes.rb
Rails.application.routes.draw do
  
  resources :stories
  resources :headlines
  resources :leadlines
  resources :quotes
  resources :atoms
  
  get 'news' => 'news#index'
  get 'news/:id' => 'news#show'
  post 'make_headline_active/:id' => 'headlines#make_headline_active', as: :make_headline_active
  post 'make_leadline_active/:id' => 'leadlines#make_leadline_active', as: :make_leadline_active
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
    <title><%= content_for?(:title) ? yield(:title) : "ProjectAlex" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <a class="hidden-xs navbar-brand" href="">Project Alex</a>
        <a class="hidden-sm hidden-md hidden-lg navbar-brand" href=""><i class="fa fa-home"></i></a>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Latest News", news_path %></li>
        </ul>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="hidden-xs col-sm-1 col-lg-2">...</div>
        <div class="col-xs-12 col-sm-10 col-lg-8">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="hidden-xs col-sm-1 col-lg-2">...</div>
      </div><!--/row-->
      
      <footer>
        <p><h6>&copy; Project Alex 2015</h6></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/authoring.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
    <title><%= content_for?(:title) ? yield(:title) : "ProjectAlex" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <a class="hidden-xs navbar-brand" href="">Project Alex</a>
        <a class="hidden-sm hidden-md hidden-lg navbar-brand" href=""><i class="fa fa-home"></i></a>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Latest News", news_path %></li>
        </ul>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-xs-12"><%= bootstrap_flash %><%= yield :main %></div></div>
      <div class="row">
        <div class="col-xs-4"><%= yield :headlines %><%= yield :leadlines %></div>
        <div class="col-xs-8"><%= yield :elements %></div></div> <!-- row -->
      
      <footer>
        <p><h6>&copy; Project Alex 2015</h6></p></footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/news.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
    <title><%= content_for?(:title) ? yield(:title) : "ProjectAlex" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <a class="hidden-xs navbar-brand" href="">Project Alex</a>
        <a class="hidden-sm hidden-md hidden-lg navbar-brand" href=""><i class="fa fa-home"></i></a>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Latest News", news_path %></li>
        </ul>
      </div>
    </div>

    <div class="container"> <!-- Story Content Section -->
      <div class="row">
        <div class="hidden-xs col-sm-1 col-lg-3">&nbsp;</div>
        <div class="col-xs-12 col-sm-10 col-lg-6">
          <%= bootstrap_flash %>
          <%= yield :news_story %>
        </div>
        <div class="hidden-xs col-sm-1 col-lg-3">&nbsp;</div>
      </div><!--/row-->
      
      <div class="row"> <!-- Similiar Stories Section -->
        <div class="hidden-xs col-sm-1 col-lg-2">&nbsp;</div>
        <div class="col-xs-12 col-sm-10 col-lg-8">
          <%= yield :similar_stories %>
        </div>
        <div class="hidden-xs col-sm-1 col-lg-2">&nbsp;</div>
      </div>
      
      <div class="row"> <!-- Sources Section -->
        <div class="hidden-xs col-sm-1 col-lg-3">&nbsp;</div>
        <div class="col-xs-12 col-sm-10 col-lg-6">
          <%= yield :sources %>
        </div>
        <div class="hidden-xs col-sm-1 col-lg-3">&nbsp;</div>
      </div>
      
      <footer>
        <p><h6>&copy; Project Alex 2015</h6></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>